#---
# tasks file for deploy-impairment-workers
#- name: Create namespace
#  k8s:
#    api_version: v1
#    kind: Namespace
#    name: "cluster-impairment-operator-system"
- name: Install dependencies
  pip:
    name:
      - openshift
      - kubernetes

- name: Deploy Daemonset
  k8s:
    definition: "{{ lookup('template', 'impairment-daemonset.yaml.j2') | from_yaml }}"
#    wait: yes
#    wait_condition:
#      type: Complete
#      status: "True"
    
#  vars:
#    student_number: "{{ item }}"

#- name: Get info about the daemonset pods
#  k8s_info:
#    kind: Pod
#    label_selectors:
#      - name = cluster-impairment
#    namespace: default
#  register: daemonset_pod_instances


#- debug:
#    var: daemonset_pod_instances

- pause:
    seconds: 2

- name: Wait for pods to be ready
  command: >
    oc wait --for=condition=Ready
    pods -l name=cluster-impairment --timeout=60s

- name: Remove Daemonset
  k8s:
    state: absent
#    kind: Daemonset
#    name: cluster-impairment-initializer
#    namespace: default
    definition: "{{ lookup('template', 'impairment-daemonset.yaml.j2') | from_yaml }}"
