---
# defaults file for deploy-impairment-workers
ansible_python_interpreter: /usr/bin/python3.8

impairment_duration: 30 # seconds
impairment_delay: 5 # seconds. It typically takes about 2-3 seconds for the Daemonset to run
impairment_interface: "ens2f0"
impairment_direction: "egress"
impairment_bandwidth: 1000 # kbit
impairment_latency: 150 # ms
impairment_loss: 0.02 # percent

impairment_link_flapping: false
impairment_link_flap_down_time: 3
impairment_link_flap_up_time: 3


node_selector_key: "node-role.kubernetes.io/worker"
node_selector_value: ""
