apiVersion: apps.redhat.com/v1alpha1
kind: ClusterImpairment
metadata:
  name: all-impairments
spec:  
  impairments:
    duration: 480 # seconds
    start_delay: 5 # seconds
    interfaces:
    - "ens2f0"
    egress:
      latency: 50 # ms. Bidirectional, so total of 100ms
      loss: 0.02 # percent  
      bandwidth: 10000 # 1000 kbit/s, about 10 mbit/s
    ingress:    
      latency: 50 # ms. Bidirectional, so total of 100ms
      loss: 0.02 # percent
      bandwidth: 10000 # 1000 kbit/s, about 10 mbit/s
    link_flapping:
      enable: true
      down_time: 30 # Seconds
      up_time: 120 # Seconds

