apiVersion: apps.redhat.com/v1alpha1
kind: ClusterImpairment
metadata:
  name: two-min-flap
spec:
  duration: 480
  start_delay: 5
  interfaces:
  - "ens2f0"
  link_flapping:
    enable: true
    down_time: 120 # Seconds
    up_time: 120 # Seconds

