apiVersion: apps.redhat.com/v1alpha1
kind: ClusterImpairment
metadata:
  name: typical-scenario
spec:
  impairments:
    duration: 30 # seconds
    start_delay: 5 # seconds
    interfaces:
    - "ens2f0"
    - "eno1"
    egress:
      latency: 50 # ms. Bidirectional, so total of 100ms
    ingress:
      latency: 50 # ms. Bidirectional, so total of 100ms
    loss: 0.02 # percent

