apiVersion: v1
kind: Pod
metadata:
  namespace: cluster-impairment-operator
  name: cluster-impairment-worker
spec:
  privileged: true
  containers:
  - name: tc
    image: quay.io/redhat-performance/cluster-impairment-worker
    env:
    - name: INTERFACE
      value: "ens2f0"
    - name: BANDWIDTH_LIMIT
      value: "1000"
    - name: DURATION
      value: "60"
    - name: EGRESS_LATENCY
      value: "100"
    - name: DRY_RUN
      value: "True"
    securityContext:
      privileged: true
#      allowPrivilegeEscalation: true
    volumeMounts:
    - mountPath: /lib/modules
      name: modprobe-modules-dir
  restartPolicy: Never
  hostNetwork: true
  dnsPolicy: Default
  volumes:
  - name: modprobe-modules-dir
    hostPath:
      path: /lib/modules
  serviceAccountName: network-access
