apiVersion: v1
kind: Pod
metadata:
  name: cluster-impairment-worker
spec:
  privileged: true
  containers:
  - name: tc
    image: quay.io/joconnel/cluster-impairment-operator-worker
    env:
    - name: INTERFACE
      value: "ens2f0"
    - name: BANDWIDTH_LIMIT
      value: "1000"
    - name: DURATION
      value: "60"
    - name: LATENCY
      value: "500"
    - name: IMPAIRMENT_DIRECTION
      value: "Both"
#    - name: DRY_RUN
#      value: "True"
    securityContext:
      privileged: true
#      allowPrivilegeEscalation: true
    volumeMounts:
    - mountPath: /lib/modules
      name: modprobe-modules-dir
  restartPolicy: Never
  hostNetwork: true
  dnsPolicy: Default
  volumes:
  - name: modprobe-modules-dir
    hostPath:
      path: /lib/modules

