apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cluster-impairment-initializer
  namespace: cluster-impairment-operator
  labels:
    k8s-app: cluster-impairment
spec:
  selector:
    matchLabels:
      name: cluster-impairment
  template:
    metadata:
      labels:
        name: cluster-impairment
    spec:
      containers:
        - name: impairment-worker
          image: quay.io/redhat-performance/cluster-impairment-worker
          env:
          - name: INTERFACE
            value: "ens2f0"
          - name: EGRESS_BANDWIDTH_LIMIT
            value: "1000"
          - name: DURATION
            value: "30"
          - name: EGRESS_LATENCY
            value: "50"
      #    - name: DRY_RUN
      #      value: "True"
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /lib/modules
            name: modprobe-modules-dir
      volumes:
      - name: modprobe-modules-dir
        hostPath:
          path: /lib/modules
      hostNetwork: true
      dnsPolicy: Default
      serviceAccountName: network-access
