# permissions for end users to edit cluster-impairments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-impairment-editor-role
rules:
- apiGroups:
  - impairment.redhat.com.redhat.com
  resources:
  - cluster-impairments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - impairment.redhat.com.redhat.com
  resources:
  - cluster-impairments/status
  verbs:
  - get
