---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for impairment.redhat.com.redhat.com/v1alpha1, Kind: Cluster-impairment
  ##
  - apiGroups:
      - impairment.redhat.com.redhat.com
    resources:
      - cluster-impairments
      - cluster-impairments/status
      - cluster-impairments/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for apps.redhat.com/v1alpha1, Kind: ClusterImpairment
  ##
  - apiGroups:
      - apps.redhat.com
    resources:
      - clusterimpairments
      - clusterimpairments/status
      - clusterimpairments/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules
