apiVersion: apps.redhat.com/v1alpha1
kind: ClusterImpairment
metadata:
  name: uneven-latency
spec:
  duration: 60
  start_delay: 5
  interfaces:
  - "ens2f0"
  ingress:
    latency: 10 # ms
  egress:
    latency: 100 # ms
  node_selector:
    key: "node-role.kubernetes.io/worker"
    value: ""
---
apiVersion: apps.redhat.com/v1alpha1
kind: ClusterImpairment
metadata:
  name: two-min-flap
spec:
  duration: 480
  start_delay: 5
  interfaces:
  - "ens2f0"
  link_flapping:
    enable: true
    down_time: 120 # Seconds
    up_time: 120 # Seconds
---
apiVersion: apps.redhat.com/v1alpha1
kind: ClusterImpairment
metadata:
  name: typical-scenario
spec:
  duration: 30 # seconds
  start_delay: 5 # seconds
  interfaces:
  - "ens2f0"
  - "eno1"
  egress:
    latency: 50 # ms. Bidirectional, so total of 100ms
  ingress:
    latency: 50 # ms. Bidirectional, so total of 100ms
  loss: 0.02 # percent
---
apiVersion: apps.redhat.com/v1alpha1
kind: ClusterImpairment
metadata:
  name: all-impairments
spec:
  duration: 480 # seconds
  start_delay: 5 # seconds
  interfaces:
  - "ens2f0"
  egress:
    latency: 50 # ms. Bidirectional, so total of 100ms
    loss: 0.02 # percent
    bandwidth: 10000 # 1000 kbit/s, about 10 mbit/s
  ingress:
    latency: 50 # ms. Bidirectional, so total of 100ms
    loss: 0.02 # percent
    bandwidth: 10000 # 1000 kbit/s, about 10 mbit/s
  link_flapping:
    enable: true
    down_time: 30 # Seconds
    up_time: 120 # Seconds

