---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterimpairments.apps.redhat.com
spec:
  group: apps.redhat.com
  names:
    kind: ClusterImpairment
    listKind: ClusterImpairmentList
    plural: clusterimpairments
    singular: clusterimpairment
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Run status
      jsonPath: .status.run_status
      name: Status
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ClusterImpairment is the Schema for the clusterimpairments API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of ClusterImpairment
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of ClusterImpairment
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
